### ISSUE TITLE
A new request to add compatibility for windows

### ISSUE THREAD

**Issue by syedaliObjects** [aubreypwd/local-tableplus#22] opened 2023-08-11 11:29 UTC
I waiting for **loacalwp-tableplus** windows addon. please add compatibility for windows.
The default database controller **Adminer** is no longer user friendly.

**Comment by aubreypwd** [comment] 2023-08-14 15:00
I do not plan to add Windows support myself, duplicate of #21

**Closed as completed by aubreypwd** 2023-08-14 15:00 UTC
Labels: wontfix
