### ISSUE TITLE
"Open TablePlus" has no response/action

### ISSUE THREAD

**Issue by FreekGille** [aubreypwd/local-tableplus#9] opened 2021-02-09 18:53 UTC
Hi! 

I recently switched from Sequel Pro to TablePlus and was happy to see this integration. When installing it through the Add-on tab, I have the "Open TablePlus" button appear correctly next to the Adminer/Sequel Pro ones but clicking the button does nothing. Using TablePlus Version 3.12.2 (358) and Local 5.9.7+5156 on macOS 11.1. 
I've tried both installing from the .tgz provided from Github and the Extension tab which have the same behaviour. Having TablePlus open or not also makes no difference.

The buttons for Adminer and Sequel Pro open up without a problem.

Thanks in advance!

**Comment by FreekGille** [comment] 2021-02-09 19:33
Did some more digging through the Develop menu. The error that is thrown when clicking is:

`/Applications/Local.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js:91 Uncaught Error: EEXIST: file already exists, symlink '/Users/me/Library/Application Support/Local/run/1UsgLJ7zl/mysql/mysqld.sock' -> '/tmp/mysql.sock'`

**Comment by rodrigo-arias** [comment] 2021-02-18 14:22
Same error here

**Comment by bgturner** [comment] 2021-02-22 16:07
@FreekGille -- That `/tmp/mysql.sock` button is likely a file for another MySQL instance (for example, one installed by Brew?) 

To get a workaround and zero in on a fix, can you try:

1. Quit Local and any other apps that would be using mysql
2. Delete the `/tmp/mysql.sock` file
3. Start Local and click the "TablePlus" button

**Comment by flowdee** [comment] 2021-02-22 16:28
Same here

**Comment by rodrigo-arias** [comment] 2021-02-23 13:27
@bgturner when removing the symlink from the `tmp` folder, Local just creates another one with the same result. Removing MySQL package from Brew didn't make a difference either.

**Comment by aubreypwd** [comment] 2021-02-25 15:57
I have some time tomorrow that I can try and look at this, thanks for reporting the issue. How it works is TablePlus uses `/tmp/mysql.sock` by default for some reason so we symlink that file to the one in local for the given site. I used to unlink it before, but I removed that so that if you wanted to open another connection you could since `/tmp/mysql.sock` would still have the connection active.

Maybe the file permissions for `/tmp/mysql.sock` are different for you guys than me? But I'll try and look at this soon! Thanks!

**Comment by aubreypwd** [comment] 2021-02-26 19:52
So first off I was able to replicate this — and it's been a bug I've been experiencing where I have to click the button twice. And I think what's happening is the unlink [here](https://github.com/aubreypwd/local-tableplus/blob/master/src/TablePlus.js#L149) isn't happening fast enough that the symlink right after is happening too soon.

**Comment by aubreypwd** [comment] 2021-02-26 20:15
Okay, this should be fixed in https://github.com/aubreypwd/local-tableplus/releases/tag/v1.0.2 — going to work with Local team to see how I get this updated version on their site. 

Thanks for all the feedback!

**Comment by aubreypwd** [comment] 2021-02-26 20:22
See https://github.com/aubreypwd/local-tableplus/issues/10 on the progress of that.

**Comment by rodrigo-arias** [comment] 2021-02-26 22:15
Hi @aubreypwd, thanks for working on this. I tried the new version without luck. I get a pretty similar error, even after deleting the temp folder and restarting Local.

``
{"thread":"renderer","stack":"Error: EEXIST: file already exists, symlink '%%site.runData%%/mysql/mysqld.sock' -> '/tmp/mysql.sock'\n    at Object.symlinkSync (fs.js:994:3)\n    at TablePlus.symlinkTmpSockFile (%%userDataPath%%/addons/local-tableplus/lib/TablePlus.js:148:12)\n    at %%userDataPath%%/addons/local-tableplus/lib/TablePlus.js:138:49\n    at FSReqCallback.oncomplete (fs.js:146:23)","level":"error","message":"EEXIST: file already exists, symlink '%%site.runData%%/mysql/mysqld.sock' -> '/tmp/mysql.sock'","timestamp":"2021-02-26T22:12:47.392Z"}
``

**Comment by FreekGille** [comment] 2021-03-09 16:32
@aubreypwd I've just downloaded and installed v1.0.2 and the issue has been resolved for me. Thanks a lot for the fix!

**Comment by flowdee** [comment] 2021-03-10 05:25
Just updated to v1.0.2 but still the same issue for me

**Comment by rodrigo-arias** [comment] 2021-03-10 14:00
@aubreypwd no problem. I'm not sure why the error persists but I can confirm that I have the correct versions. Just in case, I checked to have the code you added here https://github.com/aubreypwd/local-tableplus/commit/7a2533a3a41c3d7a103172bf0d5f2330a4d3c4c6

Local v5.10.1
TablePlus v3.12.5
TablePlus Add-on v1.0.2

**Comment by fclaussen** [comment] 2021-03-18 15:11
Same here.
If I click twice I get an error
```
Uncaught Error: EEXIST: file already exists, symlink '/Users/trewknowledge002/Library/Application Support/Local/run/kX8CW_9S_/mysql/mysqld.sock' -> '/tmp/mysql.sock'
    at Object.symlinkSync (fs.js:994)
    at TablePlus.symlinkTmpSockFile (TablePlus.js:160)
    at TablePlus.js:149
    at FSReqCallback.oncomplete (fs.js:146)
```

If I only click once, I get a warning
```
[Violation] 'click' handler took 320ms
```

**Comment by aubreypwd** [comment] 2021-03-22 15:32
This HAS to mean `fs.unlink` isn't working and is continuing despite not deleting it... I will take a look at this again, I wonder if maybe `unlink` is reporting an error to `symlinkTmpSockFile()` that I can check...

**Comment by aubreypwd** [comment] 2021-03-26 18:01
OK, so the _only_ way I can replicate this is if I do e.g. `sudo touch /tmp/mysql.sock` and then I get this error. I worked out a fix (on `master`) that will at least disable the button if we can't access the `/tmp/mysql.sock` file (and it already exists) for now... But I'm very curious why you all have `/tmp/mysql.sock` files that are not unlinkable....

Could anyone here do a `ls -lah /tmp/mysql.sock` just so I can see who owns the file? Also if you have any clue _what_ is making this file that would also help...

**Comment by aubreypwd** [comment] 2021-03-26 18:12
I've pushed https://github.com/aubreypwd/local-tableplus/releases/tag/v1.0.3 so that at least the button doesn't show as enabled if we can't unlink/modify the `/tmp/mysql.sock` file. 

I'm not sure what we can do about this e.g. if `mysql.sock` is created by `root`, etc by another service/application...

**Comment by fclaussen** [comment] 2021-03-26 18:53
@aubreypwd Here is the output of that command.
I hope this helps.

```
lrwxr-xr-x  1 trewknowledge002  wheel    89B 18 Mar 11:09 /tmp/mysql.sock -> /Users/trewknowledge002/Library/Application Support/Local/run/kX8CW_9S_/mysql/mysqld.sock
```

**Comment by rodrigo-arias** [comment] 2021-03-26 21:08
@aubreypwd the button is correctly disabled with v.1.0.3, although if I remove the tmp file manually, the button is enabled agin, but clicking returns the same error.

In my case the owner is Local itself. Is that expected?
```ls -lah /tmp/mysql.sock
lrwxr-xr-x  1 Kreppar  wheel    80B Mar 26 17:57 /tmp/mysql.sock -> /Users/Kreppar/Library/Application Support/Local/run/WKw2BY8Wm/mysql/mysqld.sock

**Comment by rodrigo-arias** [comment] 2021-03-26 21:52
I tried the following
1. Delete the file manually `rm -rf tpm/mysql.sock`
2. Remove `unlinkAndThenSymlinkTmpSockFile` so that it does not fail as the file does not exist

The result is that the exact same symlink was generated
```lrwxr-xr-x  1 Kreppar  wheel    80B Mar 26 18:28 tmp/mysql.sock -> /Users/Kreppar/Library/Application Support/Local/run/WKw2BY8Wm/mysql/mysqld.sock

**Comment by aubreypwd** [comment] 2021-03-29 15:14
Thank you all for your feedback, when I have time I think this will help out!

**Comment by aubreypwd** [comment] 2021-03-31 23:25
So can you guys give https://github.com/aubreypwd/local-tableplus/releases/tag/v1.0.5-beta.0 the kitchen sink? When you install it make sure you run `sudo rm /tmp/mysql.sock`...

What to expect:
1. First off, for things to work like normal when you boot up Local, e.g. switching sites, loading TablePlus on each site accurately, etc
2. If there IS an error check console and report back

I think I got all the problems ironed out in this one. Now, that being said, if Local cannot modify `/tmp/mysql.sock` e.g. if `root` created it or another user e.g. from another process created it, etc, there's nothing we can do about it so the button should be disabled if that is the case. I want to work in a message that tells you what is wrong but that will come in a later release...

My goal for this version is to just ensure that things are back to normal and that if you `sudo rm -Rf mysql.sock` Local can symlink things properly and connect Table Plus.

**Comment by aubreypwd** [comment] 2021-04-01 00:18
Actually checkout [v1.0.5-beta.1](https://github.com/aubreypwd/local-tableplus/releases/tag/v1.0.5-beta.1) which I think fixes the primary issue which (finally) I found out was cause because the all `fs.exists*` checks failed for `/tmp/mysql.sock` if the symlink itself pointed to a file that no longer exists (e.g. after a Local restart). So even though the file `/tmp/mysql.sock` file actually exists all the checks for it existing were failing because it linked to a file that didn't exist....

Crazy stuff.

**Comment by rodrigo-arias** [comment] 2021-04-01 00:23
Thanks for your work @aubreypwd, I'm glad you're close.

Here are some tests in case they help: https://monosnap.com/file/0ETPBbhoB2xbOIJShp3KtaBB5vLUjj

It seems that the first site I tried works, but none else. Deleting the symlink doesn't work for other sites, even after restarting Local.

**Comment by aubreypwd** [comment] 2021-04-01 00:57
@rodrigo-arias did you use `1.0.5-beta.1`?

**Comment by rodrigo-arias** [comment] 2021-04-01 01:42
@aubreypwd sorry, my previous test was with `beta.0`, `beta.1` doesn't throw any errors, which is great.

The only error I see is that only the first site I tried opens TablePlus. If I try with any other site (even a new one) I don't get errores but the app doesn't open.

What is interesting is that if I open TablePlus on the working site and without closing the connection I try to open another site, the symlink is generated and MySQL is updated.

I have no idea because only one site is generating the connection and opening the app, I have a TablePlus license so I don't think there is a limitation there.

**Comment by aubreypwd** [comment] 2021-04-01 16:04
I just had a friend test this and he is seeing the same thing. What's unique about his setup is that in `/tmp` the `mysql.sock` file already existed, e.g. something else is making that file. Though it was owned BY him (e.g. his user) so I'm not sure why Local in `beta.1` couldn't delete the file and re-symlink it.

On my machine I've just been doing `sudo touch /tmp/mysql.sock` to make a file we can't edit and it disables the button properly. But in his case the file wasn't e.g. made by `root` or anything, but still my addon couldn't delete it, or symlink it.

Also noting he got an error thrown from `readLinksync` which isn't in the code, but the error was thrown for him non-the-less. I suspect he is running Valet that is creating these files/etc, but we're unsure. 

But expect another beta to come out if I can a) replicate and b) harden my code so that at the very least if we can't symlink the file a) no errors are thrown in the process and b) we disable the button.

Thanks for your feedback @rodrigo-arias and anything in your console on _your_ error would still be helpful! Maybe it's the same error. Also an `ls -lah /tmp/mysql.sock` would also help....

**Comment by aubreypwd** [comment] 2021-04-01 16:08
@bgturner I'm not sure if this is possible, but could you unlist TablePlus until we figure this out? 1.0.3 and 1.0.4 are not stable, and I'm worried about people updating or could we roll back the version to `1.0.2`?

**Comment by rodrigo-arias** [comment] 2021-04-01 17:46
@aubreypwd no problem, glad to help. It doesn't seem like a permissions issue because of the following:
1. If I create the symlink with admin permissions `sudo touch /tmp/mysql.sock` the button disables and I get "/tmp/mysql.sock is not writable, so we can't modify it." what is perfectly to be expected.
2. If I remove the symlink, the button is enabled and when clicking it the symlink is generated `ls tmp`, I don't get any error in the console, neither in the first click nor in the following, BUT the app doesn't open.

The strange thing is that only one site opens the app. Additional test regarding this:

1. Removing the site didn't make others sites work.
2. Exporting the site, deleting it, and re-importing it keeps working.
3. Creating a new site with the same settings didn't help 
4. Open the connection with the working site, and without closing it, click Open TablePlus on another site, update the symlink and TablePlus loads the new database.

Just in case `ls -lah /tmp/mysql.sock`
```
lrwxr-xr-x  1 Kreppar  wheel    80B Apr  1 14:37 /tmp/mysql.sock -> /Users/Kreppar/Library/Application Support/Local/run/ti6Mzrsn5/mysql/mysqld.sock
```
I have no idea why only one specific site opens the app, but it seems like the last missing piece.

**Comment by aubreypwd** [comment] 2021-04-13 20:26
I think it's because of how unlink works in Node. It seems to NOT be unlinking the file so it can be re-linked. Next time I get to look at this that's what I'm going to be looking at, is why it's not actually unlinking the file.

unlink in Node throws an error, which we catch now, but then the button doesn't do anything. Checks up the like (e.g. access/write/etc) all check out, but then when it actually tries to unlink it it's unable to unlink it, causing the button to not do anything....

I just need to figure out why that's not working or maybe re-think another way to do this...

**Comment by aubreypwd** [comment] 2021-04-30 18:48
I have a new [beta](https://github.com/aubreypwd/local-tableplus/releases/tag/v1.0.5-beta.2) out that always unlinks the file when it exists (vs trying to overwrite) and catches more thrown errors along the way. If anyone here can give it a try and report back that would be great.

**Comment by rodrigo-arias** [comment] 2021-04-30 19:14
Hi @aubreypwd, I tried it and I got the same. Only one site opens TablePlus, no console errors on any site.
Something that may help, the symlink is working correctly, I have verified that when I click the button on another site, the symlink is updated, although it doesn't open the app.

Site 1
`ls -lah mysql.sock
lrwxr-xr-x  1 Kreppar  wheel    80B Apr 30 16:07 mysql.sock -> /Users/Kreppar/Library/Application Support/Local/run/Ct5eij3tb/mysql/mysqld.sock`

Site 2
`ls -lah mysql.sock
lrwxr-xr-x  1 Kreppar  wheel    80B Apr 30 16:09 mysql.sock -> /Users/Kreppar/Library/Application Support/Local/run/ti6Mzrsn5/mysql/mysqld.sock`

**Comment by aubreypwd** [comment] 2021-04-30 19:59
Yeah I did some testing just now with a work buddy and I see the issue. The issue is mainly around the fact that all Node's tests on e.g. if file exists, writeable, etc are of the file it's SYMLINKED to not the actual link in `/tmp`.

Trying to see if I can do something else other than symlink here, e.g. copy the file, etc. 

Thanks for your feedback.

**Comment by aubreypwd** [comment] 2021-04-30 21:16
I have yet _another_ [beta](https://github.com/aubreypwd/local-tableplus/releases/tag/v1.0.5-beta.3) that might work (it's working for me now), but it still can't fix the issue around when `/tmp/mysql.sock` is e.g. owned by another user or something. It will turn red if it cannot successfully symlink.

But another buddy at work tested it and had a totally different problem where the symlink was being created, but the button wasn't actually opening TablePlus. It may be something unique to his machine (and maybe a separate issue).

**Comment by rodrigo-arias** [comment] 2021-04-30 22:52
I tried beta 3 and the result is the same. The symlink updates successfully but TablePlus only opens on one site.

I still don't understand why it only works on one site, I don't see anything special on that site. I have tried creating another with identical configuration but only the first one works.

Thanks for still working on this.

**Comment by aubreypwd** [comment] 2021-05-05 16:06
> I still don't understand why it only works on one site, I don't see anything special on that site.

There is nothing special, on my machine I'm able to switch sites and open each database, so this has me worried either a) my distribution of my version in the `.tar.gz` is not accurate or b) you aren't running the beta3.

But if you have two sites running you should be able to open each's database in TablePlus....

**Comment by aubreypwd** [comment] 2021-05-06 21:20
Hey everyone, checkout [this video](https://youtu.be/0cpW6MD2O6k) where I demo a bit how this is working on my machine. I think it's release ready, but wanted to show everyone _here_ my experience (and the experience of a few others) before I go pushing out a release for any final feedback.

Thanks!

**Comment by AdamWills** [comment] 2021-05-07 13:29
@aubreypwd Just want to chime in to say that the latest release is working great for me after encountering the original issue!

**Comment by aubreypwd** [comment] 2021-05-07 15:48
> Just want to chime in to say that the latest release is working great for me after encountering the original issue!

Just want to be 💯, you mean `v1.0.5-beta.3`?

**Comment by AdamWills** [comment] 2021-05-07 18:21
> > Just want to chime in to say that the latest release is working great for me after encountering the original issue!
> 
> @AdamWills Just want to be 💯, you mean `v1.0.5-beta.3`?

Yes, beta.3!

**Comment by rodrigo-arias** [comment] 2021-05-07 19:27
@aubreypwd after several tests, I think I found the issue. You may need to process the site data on [this line](https://github.com/aubreypwd/local-tableplus/blob/master/src/TablePlus.js#L130) for cases in which the name of the site contains more than one word.

You can see some tests [here](https://monosnap.com/file/OqpHdCJ4bpp8fPkGu4GLximDE7Np4j)

The good news is that the original issue is fixed in `v1.0.5-beta.3`
Thanks

**Comment by aubreypwd** [comment] 2021-05-10 16:20
@rodrigo-arias this is a new issue, see https://github.com/aubreypwd/local-tableplus/issues/12 

Thanks for catching this! I have a habit of naming sites with _no_ spaces and use `-` so I would have never encountered this. I will also try and see if I can get this fixed for the next release. Also thanks for confirming this is resolved in the latest `beta-3`!

**Closed** 2021-05-28 15:23 UTC
Labels: bug

**Comment by flowdee** [comment] 2021-05-29 10:34
Updating to v1.0.5 worked fine for me and solved the issue. Thanks @aubreypwd 🥳
