### ISSUE TITLE
Doesn't work with SetApp

### ISSUE THREAD

**Issue by losbenos** [aubreypwd/local-tableplus#19] opened 2022-05-25 11:05 UTC
I have tableplus installed through my setapp subscription but it isn't recognised by my installation of LocalWP
I'm guessing that there are slightly different environmental variables at play but it would be great if this could be updated.

**Comment by aubreypwd** [comment] 2022-06-09 21:45
Duplicate of #16 and #13

**Closed as completed by aubreypwd** 2022-06-09 21:45 UTC
